FROM node:22

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 8545

CMD npx hardhat node & \
    sleep 5 && \
    npx hardhat run scripts/deploy.js --network localhost && \
    tail -f /dev/null
